version: '3.1'

services:
  dht1:
    image: fcon_dht
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    container_name: dht1
    restart: always
    hostname: dht1
    tty: true
    network_mode: host
    volumes:
      - /home/javi/Nextcloud/Universidad/Master/1_Cuatri/FCON/final/dht/jar:/application
      - /home/javi/Nextcloud/Universidad/Master/1_Cuatri/FCON/LAB_1/apache-zookeeper-3.6.3-bin/lib:/zookeeper-lib
      - /home/javi/Nextcloud/Universidad/Master/1_Cuatri/FCON/LAB_1/apache-zookeeper-3.6.3-bin/bin:/zookeeper-bin


  dht2:
    image: fcon_dht
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    container_name: dht2
    restart: always
    hostname: dht2
    tty: true
    network_mode: host
    volumes:
      - /home/javi/Nextcloud/Universidad/Master/1_Cuatri/FCON/final/dht/jar:/application
      - /home/javi/Nextcloud/Universidad/Master/1_Cuatri/FCON/LAB_1/apache-zookeeper-3.6.3-bin/lib:/zookeeper-lib
      - /home/javi/Nextcloud/Universidad/Master/1_Cuatri/FCON/LAB_1/apache-zookeeper-3.6.3-bin/bin:/zookeeper-bin
      
  dht3:
    image: fcon_dht
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    container_name: dht3
    restart: always
    hostname: dht3
    tty: true
    network_mode: host
    volumes:
      - /home/javi/Nextcloud/Universidad/Master/1_Cuatri/FCON/final/dht/jar:/application
      - /home/javi/Nextcloud/Universidad/Master/1_Cuatri/FCON/LAB_1/apache-zookeeper-3.6.3-bin/lib:/zookeeper-lib
      - /home/javi/Nextcloud/Universidad/Master/1_Cuatri/FCON/LAB_1/apache-zookeeper-3.6.3-bin/bin:/zookeeper-bin
volumes:
  application:
  zookeeper-lib:
  zookeeper-bin:



  # zoo1:
  #   # image: zookeeper:3.6.3
  #   image: fcon.zookeeper
  #   container_name: zoo1
  #   restart: always
  #   hostname: zoo1
  #   ports:
  #     - 2181:2181
  #   environment:
  #     ZOO_MY_ID: 1
  #     ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  # zoo2:
  #   # image: zookeeper:3.6.3
  #   image: fcon.zookeeper
  #   container_name: zoo2
  #   restart: always
  #   hostname: zoo2
  #   ports:
  #     - 2182:2181
  #   environment:
  #     ZOO_MY_ID: 2
  #     ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  # zoo3:
  #   # image: zookeeper:3.6.3
  #   image: fcon.zookeeper
  #   container_name: zoo3
  #   restart: always
  #   hostname: zoo3
  #   ports:
  #     - 2183:2181
  #   environment:
  #     ZOO_MY_ID: 3
  #     ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

