version: '3.1'

services:
  dht1:
    image: fcon_dht
    build:
     context: .
     dockerfile: ./Dockerfile
    container_name: dht1
    restart: always
    hostname: dht1
    tty: true
    network_mode: host
    volumes:
      - ${PWD}/jar:/application


  dht2:
    image: fcon_dht
    build:
     context: .
     dockerfile: ./Dockerfile
    container_name: dht2
    restart: always
    hostname: dht2
    tty: true
    network_mode: host
    volumes:
      - ${PWD}/jar:/application
      
  dht3:
    image: fcon_dht
    build:
     context: .
     dockerfile: ./Dockerfile
    container_name: dht3
    restart: always
    hostname: dht3
    tty: true
    network_mode: host
    volumes:
      - ${PWD}/jar:/application
volumes:
  application:

